# Generated by Django 4.1.2 on 2022-11-16 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chest',
            new_name='Bag',
        ),
        migrations.RenameModel(
            old_name='Item',
            new_name='Deed',
        ),
        migrations.RenameField(
            model_name='deed',
            old_name='chest',
            new_name='bag',
        ),
    ]
