# Generated by Django 4.1.2 on 2022-11-23 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_discipline_student_student_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
    ]
