# Generated by Django 4.1.2 on 2022-11-23 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_first_name_student_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_courses',
            name='name',
        ),
    ]
