# Generated by Django 4.1.3 on 2022-12-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=3)),
            ],
        ),
    ]
