# Generated by Django 4.1.3 on 2022-12-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_fan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fan',
            name='age',
            field=models.IntegerField(),
        ),
    ]
