# Generated by Django 4.1.3 on 2022-12-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_fan_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fan',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
