# Generated by Django 4.1.3 on 2022-12-08 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_fanclub_place_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FanClub',
            new_name='Fan',
        ),
    ]
